/** @type {import('style-dictionary').Config} */
export default {
  source: ["tokens/tokens.json"],
  platforms: {
    css: {
      transformGroup: "css",
      prefix: "cenno",
      buildPath: "src/styles/",
      files: [
        {
          destination: "tokens.css",
          format: "css/variables",
          options: {
            selector: ":root",
            outputReferences: false,
            fileHeader: "cenno-header",
          },
        },
      ],
    },
  },
  hooks: {
    fileHeaders: {
      "cenno-header": () => [
        "cenno design tokens — generated by Style Dictionary",
        "DO NOT EDIT — source of truth: tokens/tokens.json",
      ],
    },
  },
};
